name: PR Automation on Self-Hosted Runner

on:
  pull_request:
    branches:
      - added_new_bucket_006

jobs:
  self-hosted-task:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Script on PR
        run: |
          echo " Pull Request detected!"
          echo "ğŸ› ï¸Running automation on self-hosted runner..."
          date
          echo "âœ”ï¸Task complete."
